In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv(r'C:\Users\User\Downloads\Data Analyst Project\Upi_Fraud_Analysis\Data\synthetic_indian_upi_fraud_data.csv')

# Basic dataset inspection
print("DATASET SHAPE")
df.shape

DATASET SHAPE

(10000, 19)

In [21]:
print("COLUMN NAMES")
df.columns.tolist()

COLUMN NAMES

['TransactionID',
 'UserID',
 'Amount',
 'Timestamp',
 'MerchantCategory',
 'TransactionType',
 'DeviceID',
 'IPAddress',
 'Latitude',
 'Longitude',
 'AvgTransactionAmount',
 'TransactionFrequency',
 'UnusualLocation',
 'UnusualAmount',
 'NewDevice',
 'FailedAttempts',
 'FraudFlag',
 'PhoneNumber',
 'BankName']

In [22]:
print("FIRST 5 ROWS")
df.head()

FIRST 5 ROWS

,TransactionID,UserID,Amount,Timestamp,MerchantCategory,TransactionType,DeviceID,IPAddress,Latitude,Longitude,AvgTransactionAmount,TransactionFrequency,UnusualLocation,UnusualAmount,NewDevice,FailedAttempts,FraudFlag,PhoneNumber,BankName
0,842835309389,b0b99baa-1fd2-41e5-ac94-37aa0ec862f9,8589.00,2024-01-22 03:59:58,Electronics,P2M,42296fa1-8d7a-478c-a8c9-590b9d14cdb9,75.122.84.213,23.354478,-40.536076,670.31,5/day,False,True,False,2,True,2798604680,Bank of Baroda
1,592863054785,0cc467c5-8b71-4ba4-9c75-4a9e2bec2c8c,9090.54,2024-07-01 13:43:33,Electronics,P2M,e566b8a8-17c3-4372-9e07-e4c4eb3113b7,16.110.81.53,-62.956912,-102.511919,7265.96,3/day,False,True,False,2,False,3614149152,ICICI Bank
2,373481869464,f7de03ee-b7f5-4568-8ba2-e889bced4d88,8814.41,2024-04-02 05:23:39,Electronics,P2P,897d0824-bc4f-4ee7-9bfb-c8eea31b2ca2,6.47.215.37,-13.112830,-18.978059,8750.89,3/day,True,False,True,3,False,912661191911,ICICI Bank
3,285572156436,456b3f39-e9cc-429f-8568-125612c12987,3971.25,2024-06-14 16:13:43,Restaurants,P2P,a4d2f5ef-19c7-4baa-b3ea-b04069d65021,214.166.195.254,-23.898771,81.760634,8348.14,1/day,True,True,False,4,False,916358088125,State Bank of India
4,874207772966,7b4b734d-f0c5-4dce-8b9c-0b2e226abc86,4376.74,2024-07-16 03:22:40,Groceries,P2M,8aee664a-fb51-4e74-98a1-cf632a02cd27,151.99.121.13,11.383999,12.669192,1719.74,1/day,True,True,False,0,False,5132838721,ICICI Bank

In [23]:
print("DATA TYPES & NON-NULL VALUES")
df.info()

DATA TYPES & NON-NULL VALUES
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TransactionID         10000 non-null  int64
 1   UserID                10000 non-null  str
 2   Amount                10000 non-null  float64
 3   Timestamp             10000 non-null  str
 4   MerchantCategory      10000 non-null  str
 5   TransactionType       10000 non-null  str
 6   DeviceID              10000 non-null  str
 7   IPAddress             10000 non-null  str
 8   Latitude              10000 non-null  float64
 9   Longitude             10000 non-null  float64
 10  AvgTransactionAmount  10000 non-null  float64
 11  TransactionFrequency  10000 non-null  str
 12  UnusualLocation       10000 non-null  bool
 13  UnusualAmount         10000 non-null  bool
 14  NewDevice             10000 non-null  bool
 15  FailedAttempts        10000 non-null  int64
 16  FraudFlag             10000 non-null  bool
 17  PhoneNumber           10000 non-null  int64
 18  BankName              10000 non-null  str
dtypes: bool(4), float64(4), int64(3), str(8)
memory usage: 1.2 MB

In [24]:
print("STATISTICAL SUMMARY")
df.describe(include="all")

STATISTICAL SUMMARY

,TransactionID,UserID,Amount,Timestamp,MerchantCategory,TransactionType,DeviceID,IPAddress,Latitude,Longitude,AvgTransactionAmount,TransactionFrequency,UnusualLocation,UnusualAmount,NewDevice,FailedAttempts,FraudFlag,PhoneNumber,BankName
count,1.000000e+04,10000,10000.000000,10000,10000,10000,10000,10000,10000.000000,10000.000000,10000.000000,10000,10000,10000,10000,10000.000000,10000,1.000000e+04,10000
unique,NaN,10000,NaN,9997,7,2,10000,10000,NaN,NaN,NaN,3,2,2,2,NaN,2,NaN,6
top,NaN,b0b99baa-1fd2-41e5-ac94-37aa0ec862f9,NaN,2024-05-04 13:00:37,Electronics,P2M,42296fa1-8d7a-478c-a8c9-590b9d14cdb9,75.122.84.213,NaN,NaN,NaN,1/day,False,False,False,NaN,False,NaN,ICICI Bank
freq,NaN,1,NaN,2,1492,5029,1,1,NaN,NaN,NaN,3356,5007,5040,5015,NaN,9035,NaN,1723
mean,5.515428e+11,NaN,5004.460629,NaN,NaN,NaN,NaN,NaN,0.117162,0.168406,4988.532019,NaN,NaN,NaN,NaN,2.012600,NaN,3.085201e+11,NaN
std,2.595428e+11,NaN,2881.189782,NaN,NaN,NaN,NaN,NaN,52.080902,104.868717,2887.007255,NaN,NaN,NaN,NaN,1.416913,NaN,4.290684e+11,NaN
min,1.000276e+11,NaN,2.200000,NaN,NaN,NaN,NaN,NaN,-89.981366,-179.997289,1.550000,NaN,NaN,NaN,NaN,0.000000,NaN,1.593770e+05,NaN
25%,3.269720e+11,NaN,2526.945000,NaN,NaN,NaN,NaN,NaN,-45.123437,-90.746018,2497.180000,NaN,NaN,NaN,NaN,1.000000,NaN,3.809523e+09,NaN
50%,5.527816e+11,NaN,4951.010000,NaN,NaN,NaN,NaN,NaN,0.502523,0.373569,4947.515000,NaN,NaN,NaN,NaN,2.000000,NaN,7.582981e+09,NaN
75%,7.787159e+11,NaN,7528.650000,NaN,NaN,NaN,NaN,NaN,45.606327,91.905884,7487.210000,NaN,NaN,NaN,NaN,3.000000,NaN,9.124914e+11,NaN
max,9.997475e+11,NaN,9999.120000,NaN,NaN,NaN,NaN,NaN,89.976634,179.971566,9998.970000,NaN,NaN,NaN,NaN,4.000000,NaN,9.199982e+11,NaN

In [25]:
print("MISSING VALUES")
df.isnull().sum()

MISSING VALUES

TransactionID           0
UserID                  0
Amount                  0
Timestamp               0
MerchantCategory        0
TransactionType         0
DeviceID                0
IPAddress               0
Latitude                0
Longitude               0
AvgTransactionAmount    0
TransactionFrequency    0
UnusualLocation         0
UnusualAmount           0
NewDevice               0
FailedAttempts          0
FraudFlag               0
PhoneNumber             0
BankName                0
dtype: int64

In [26]:
print("DUPLICATE ROWS")
df.duplicated().sum()

DUPLICATE ROWS

np.int64(0)

In [27]:
print("FRAUD DISTRIBUTION")
df["FraudFlag"].value_counts()

FRAUD DISTRIBUTION

FraudFlag
False    9035
True      965
Name: count, dtype: int64

In [28]:
print("FRAUD RATE")
print(f"{df['FraudFlag'].mean() * 100:.2f}%")

FRAUD RATE
9.65%